In [4]:
import numpy as np


## 넘파이조지기

In [315]:
'''
target
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])
       
'''


a = np.full((3,3), True, dtype=bool)
# full((x,y), 채울 값, dtype으로 설정가능)
b = np.array([[True for n in range(3)]for a in range(3)], dtype=bool)

In [295]:
# target array([1, 3, 5, 7, 9])

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

# (aarr % 2 == 1) : array([False,  True, False,  True, False,  True, False,  True, False, True]) -> 불린형 어레이로 도출가능
# arr[arr % 2 == 1] : []안의 값이 True 인 것만 반환 


array([1, 3, 5, 7, 9])

In [297]:
#target  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1] = -1 # True 인값(array([1, 3, 5, 7, 9])에 -1 할당 
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [318]:
#target  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.where(arr % 2 == 1, -1 ,arr)) # 첫 번째 인자 : 조건, ex) arr % 2 == 1
                                       # 두 번째 인자 : 조건을 만족했을 때의 값, ex) -1
                                       # 세 번째 인자 : 조건을 만족하지 않았을 때의 값, ex) arr


arr


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [299]:
a = np.arange(10).reshape(2,-1) 

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [317]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b], axis=0) # concatenate([a에 b를 연결], axis, default = 0)

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [319]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b] , axis= 1)

# np.hstack([a, b])
# np.r_[[a],[b]]

# a = np.array([1,2,3])
# b = [n for n in a for m in a]
# np.concatenate([b,a,a])

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [320]:
# target array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# c , d = set(a)&set(b)
# np.array((c,d))

np.unique(a[a==b])
np.intersect1d(a,b)

array([2, 4])

In [305]:
# target array([1,2,3,4]) a - b 

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.unique(a[a!=b[::-1]])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [306]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [307]:
a = np.array([2, 6, 1, 9, 10, 3, 27])


a[(a >= 5) & (a <= 10)]

a[np.where((a >= 5) & (a <= 10))]


[ 6  9 10]
[ 6  9 10]


In [308]:
def pair_max(x, y):

    for n in range(len(x)):

        if x[n] >= y[n]:
            x[n] = x[n]

        else:
            x[n] = y[n]

        return x
        

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])



# pair_max(a, b)


#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


In [309]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float]) # vectorize 함수는 넘파이 배열의 각 원소에 함수를 적용할 수 있도록 해주는 함수
                                            # pyfunc: 배열의 각 원소에 적용할 함수
                                            # otypes: 출력값의 데이터 타입. 기본값은 None이며, 이 경우 출력값의 데이터 타입은 입력값의 데이터 타입과 같음

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


array([6., 7., 9., 8., 9., 7., 5.])

In [310]:
arr = np.arange(9).reshape(3,3)
arr2 = np.arange(9).reshape(3,3)

a = arr[0::,0::3]
b = arr2[0::,1::2]

arr[0::,1::2] = a
arr[0::,0::3] = b

arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [311]:
arr = np.arange(9).reshape(3,3)

arr[:,[1,0,2]] # arr[[]] [index번호로 정렬가능]

arr[[1,0,2]]

arr[::-1]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [321]:
arr2  = np.random.randint(5,10,size=(5,3)) + np.random.rand(5,3) #randint(시작n, 종료n, size=) / rand(x,y) x,y 사이즈에 0~1 사이에 float 생성
arr2

array([[6.86930502, 8.01063271, 6.83552718],
       [8.21024121, 7.8056624 , 7.90105657],
       [9.35560105, 8.3706579 , 8.23838321],
       [6.93686947, 8.4592091 , 6.18805663],
       [6.46175988, 6.44232018, 7.20766114]])

In [291]:
rand_arr = np.random.random((5,3))
rand_arr.round(3)

array([[0.7  , 0.548, 0.534],
       [0.793, 0.997, 0.157],
       [0.431, 0.026, 0.134],
       [0.738, 0.185, 0.223],
       [0.571, 0.196, 0.851]])